config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true


  belongs_to :author,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :User

  belongs_to :post

  belongs_to :parent_comment,
  required: false

  has_many :child_comments,
  primary_key: :id,
  foreign_key: :parent_comment_id,
  class_name: :Comment
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author, presence: true
  validates :sub_ids, length: { minimum: 1 }

  has_many :post_subs, dependent: :destroy, inverse_of: :post

  belongs_to :author,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "User"

  has_many :subs,
  through: :post_subs,
  source: :sub

  has_many :comments


end

app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post, :sub, presence: true
  validates :sub_id, uniqueness: { scope: :post_id }

  belongs_to :post
  belongs_to :sub

end

app/models/sub.rb
class Sub < ApplicationRecord
validates :title, :description, :moderator, presence: true


  belongs_to :moderator,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: :User

has_many :post_subs, dependent: :destroy, inverse_of: :sub

has_many :posts,
through: :post_subs,
source: :post

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :posts
  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)
    return nil unless @user
    @user.valid_pw?(password) ? @user : nil
  end

  def password=(password)
    @passowrd = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_pw?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    helper_method :current_user, :require_signed_in

    def current_user
      @current_user ||= User.find_by_session_token(session[:session_token])
      # return @current_user if @current_user
      # nil
    end

    def require_signed_in
      redirect_to new_session_url unless current_user
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    # @comment.post_id = @comment.post

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def edit
    if @post.user_id == current_user.id
      @post = Post.find(params[:id])
    else
      flash[:errors] = ["prohibit editing from non-moderator"]
      redirect_to subs_url
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.user_id == current_user.id && @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])

    if @post.user_id == current_user.id
      @post.destroy
    else
      flash[:errors] = @post.errors.full_messages
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :user_id, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      session[:session_token] = @user.session_token
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid creds"]
      render :new
    end
  end

  def destroy
    current_user.reset_session_token
    session[:session_token] = nil
    redirect_to subs_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  # before_action :require_signed_in, only: [:new, :create]

  def edit
    if @sub.user_id == current_user.id
      @sub = Sub.find(params[:id])
    else
      flash[:errors] = ["prohibit editing from non-moderator"]
      redirect_to subs_url
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.user_id == current_user.id && @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:session_token] = @user.session_token
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def print_sub_comments(comment)
    unless comment.child_comments
      puts
      return link_to comment.content, comment_url(comment)
    else
      comment.child_comments.each do |child_comment|
        "<br>".html_safe
        print_sub_comments(child_comment)
      end
    end
    puts
    link_to comment.content, comment_url(comment)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Add Comment</h1>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="">Content</label>
  <input id="Content" type="text" name="comment[content]">
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">

  <input type="submit" value="Add Comment">
</form>
<%= flash[:errors] %>

app/views/comments/show.html.erb
<h1>Reply to comment</h1>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="">Content</label>
  <input id="Content" type="text" name="comment[content]">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= params[:comment_id] %>">


  <input type="submit" value="Reply to comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if current_user %>
      <%= current_user.username %>
      <%= link_to "Create a Sub!", new_sub_url %>
      <%= link_to "All Subs", subs_url %>
      <%= button_to "Sign Out", session_url, method: :delete %>
    <% else %>
      <%= link_to "Sign_In", new_session_url %>
      <%= link_to "Sign_Up", new_user_url %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method="post">
 <input type="text" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="post[user_id]" value="<%= current_user.id %>">

  <label for="">Title</label>
  <input id="Title" type="text" name="post[title]">

  <label for="">URL</label>
  <input id="URL" type="text" name="post[description]">

  <label for="">content</label>
  <input id="URL" type="text" name="post[content]">

  <label>Tags</label>

  <input type="hidden" name="post[sub_ids][]" value="">

  <label>Tags</label>

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if @post.sub_ids.include?(sub.id)%>>">
    </label>
  <% end %>


  <input type="submit" value="Edit Post">
</form>

app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


  <label for="">Title</label>
  <input id="Title" type="text" name="post[title]">

  <label for="">URL</label>
  <input id="URL" type="text" name="post[url]">

  <label for="">content</label>
  <input id="content" type="text" name="post[content]">



  <!-- <input type="hidden" name="post[sub_ids][]" value=""> -->

  <label>Subs</label>

  <% Sub.all.each do |sub1| %>
    <label><%= sub1.title %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= sub1.id %>"
    </label>
  <% end %>


  <input type="submit" value="New Post">
</form>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h1>By <%= @post.author.username %></h1>
<%= @post.content %>

<br>

  <%= link_to "Add comment:", new_post_comment_url(@post)%>
  <br>

<% @post.comments.where(parent_comment_id: nil).each do |comment| %>
  <%= print_sub_comments(comment) %>
  <br>
  <%= link_to comment.content, comment_url(comment) %>

<% end %>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="">Title</label>
  <input id="Title" type="text" name="sub[title]">

  <label for="">Description</label>
  <input id="Description" type="text" name="sub[description]">

  <input type="submit" value="Edit Sub">
</form>

app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
  <% @subs.each do |sub1| %>
  <li>
  <%= link_to sub1.title, sub_url(sub1) %>
  </li>
  <% end  %>
</ul>

app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%= subs_url %>" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="">Title</label>
  <input id="Title" type="text" name="sub[title]">

  <label for="">Description</label>
  <input id="Description" type="text" name="sub[description]">

  <input type="submit" value="New Sub">
</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h3>Description</h3>
<h3><%= @sub.description %></h3>

<%= link_to "Make New Post!", new_post_url %>

<ul>
  <% @sub.posts.each do |post| %>
  <li>
  <%= link_to post.title, post_url(post)%>
  </li>
  <% end  %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="">Username</label>
  <input id="Username" type="text" name="user[username]">

  <label for="">Password</label>
  <input id="Password" type="text" name="user[password]">

  <input type="submit" value="Sign Up">
</form>